version: '3'

services:
  durak_db:
    container_name: durak_db
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    env_file:
      - ../.env_prod
    restart: unless-stopped
    volumes:
      - durak_pgdata:/var/lib/postgresql/data
  durak_backend:
    container_name: durak_backend
    restart: unless-stopped
    build:
      context: ../
    env_file:
      - ../.env_prod
    ports:
      - "8888:8000"
    depends_on:
      - durak_db
      - durak_redis_stack
    volumes:
      - durak_static:/app/start_all_template/static
      - durak_media:/app/media
    command:
      - /start
  durak_redis_stack:
    image: redis/redis-stack-server:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - durak_redis:/data/
    container_name: durak_redis_stack
  celery_worker:
    container_name: durak_celery_worker
    build:
      context: ../.
    restart: unless-stopped
    env_file:
      - ../.env_prod
    depends_on:
      - durak_db
      - durak_redis_stack
      - durak_backend
    command: celery -A configs worker --loglevel=info
  celery_beat:
    container_name: durak_celery_beat
    build:
      context: ../
    restart: unless-stopped
    env_file:
      - ../.env_prod
    depends_on:
      - durak_db
      - durak_redis_stack
      - durak_backend
    command: celery -A configs beat -l INFO  --scheduler django_celery_beat.schedulers:DatabaseScheduler
volumes:
  durak_pgdata:
  durak_static:
  durak_media:
  durak_redis: