# Generated by Django 4.1.2 on 2022-11-03 08:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название вопроса')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание вопроса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Часто задаваемые вопросы',
                'verbose_name_plural': 'Часто задаваемые вопросы',
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honesty_game', ckeditor.fields.RichTextField(verbose_name='Как мне убедиться в честности игры?')),
                ('roll', ckeditor.fields.RichTextField(verbose_name='Рулетка')),
                ('agreement', ckeditor.fields.RichTextField(verbose_name='Пользовательское соглашение')),
                ('about_us', ckeditor.fields.RichTextField(verbose_name='О нас')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание снизу')),
                ('support_email', models.EmailField(max_length=254, verbose_name='Почта для связи с поддержкой')),
                ('url_vk', models.URLField(verbose_name='Ссылка на VK')),
                ('url_youtube', models.URLField(verbose_name='Ссылка на Youtube')),
            ],
            options={
                'verbose_name': 'Контент сайта',
                'verbose_name_plural': 'Контент сайта',
            },
        ),
    ]
